comment

diff --git a/.github/workflows/kubescape.yaml b/.github/workflows/kubescape.yaml
--- a/.github/workflows/kubescape.yaml
+++ b/.github/workflows/kubescape.yaml
@@ -9,6 +9,7 @@
           uses: actions/checkout@v3
 
         - name: Kubescape Scan
+          id: kubescape
           run: |
               echo "Installing Kubescape..."
               curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
@@ -18,8 +19,10 @@
               echo "Starting Kubescape scan..."
               kubescape version
             
-              kubescape scan -v framework nsa,cis-eks-t1.2.0 .
+              kubescape scan --severity-threshold high --keep-local -l debug framework nsa,mitre,soc2,cis-eks-t1.2.0 . -v
               
-              # Comment in PR
-              echo "Commenting on PR"
-              kubescape scan -l error framework nsa,cis-eks-t1.2.0 . | awk '/^Run with .*verbose/,EOF' | tail -n +2 | awk '/^│ *(High|Critical)/ || /^├|^┌|^└/ || /Resource Summary/'
+        - name: Check Kubescape Results
+            if: steps.kubescape.outcome == 'failure'
+            run: |
+              echo "::error::There is Critical or High findings detected that will block this PR until resolved. Please fix and re-run the workflow"
+              exit 1
